/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientwcf;

import adapters.AgenciaAdapter;
import adapters.ClientAdapter;
import adapters.ContaCorrenteAdapter;
import controllers.AgenciasJpaController;
import controllers.ClientesJpaController;
import controllers.ContacorrentesJpaController;
import java.awt.Cursor;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.swing.table.DefaultTableModel;
import model.Agencias;
import model.Clientes;
import model.Contacorrentes;
import wcf.*;

/**
 *
 * @author Danilo
 */
public class Frame extends javax.swing.JFrame {

    private final EntityManagerFactory emf;

    /**
     * Creates new form Frame
     */
    public Frame() {
        emf = javax.persistence.Persistence.createEntityManagerFactory("mymoney?zeroDateTimeBehavior=convertToNullPU");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ClientesJtable = new javax.swing.JTable();
        BaixarJButton = new javax.swing.JButton();
        ListarJButton = new javax.swing.JButton();
        ClientesLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ClientesJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Born Date", "Acc Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ClientesJtable);

        BaixarJButton.setText("Baixar");
        BaixarJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BaixarJButtonMouseClicked(evt);
            }
        });

        ListarJButton.setText("Listar");
        ListarJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListarJButtonMouseClicked(evt);
            }
        });

        ClientesLabel.setText("Clientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BaixarJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ListarJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClientesLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(ClientesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BaixarJButton)
                    .addComponent(ListarJButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListarJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListarJButtonMouseClicked
        realizarBusca();
    }//GEN-LAST:event_ListarJButtonMouseClicked

    private void BaixarJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BaixarJButtonMouseClicked
        Service1 svc = new Service1();

        ArrayOfAccount accs = svc.getBasicHttpBindingIService1().getAllAccounts();
        ArrayOfAgency agcs = svc.getBasicHttpBindingIService1().getAllAgencyes();
        ArrayOfClient clts = svc.getBasicHttpBindingIService1().getAllClients();

        AgenciaAdapter agenciaAdapter = new adapters.AgenciaAdapter();
        List<Agencias> agencias = agenciaAdapter.parser(agcs);

        ClientAdapter clientAdapter = new adapters.ClientAdapter();
        List<Clientes> clientes = clientAdapter.parser(clts);

        ContaCorrenteAdapter contaCorrenteAdapter = new adapters.ContaCorrenteAdapter();
        List<Contacorrentes> contasContacorrentes = contaCorrenteAdapter.parser(accs, agencias, clientes, clts);

        AgenciasJpaController ajc = new AgenciasJpaController(emf);
        for (Agencias agencia : agencias) {
            ajc.create(agencia);
        }

        ClientesJpaController cjc = new ClientesJpaController(emf);
        for (Clientes cliente : clientes) {
            cjc.create(cliente);
        }

        ContacorrentesJpaController ccjc = new ContacorrentesJpaController(emf);
        for (Contacorrentes contas : contasContacorrentes) {
            ccjc.create(contas);
        }
    }//GEN-LAST:event_BaixarJButtonMouseClicked

    private void realizarBusca() {
        Cursor cursor = Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR);
        this.setCursor(cursor);

        ClientesJpaController cjc = new ClientesJpaController(emf);
        List<Clientes> list = cjc.findClientesEntities();

        DefaultTableModel model = (DefaultTableModel) ClientesJtable.getModel();

        limparTabela(model);
        preencherTabela(model, list);

        cursor = Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR);
        this.setCursor(cursor);
    }

    private void limparTabela(DefaultTableModel model) {
        if (model.getRowCount() > 0) {
            for (int i = model.getRowCount() - 1; i > -1; i--) {
                model.removeRow(i);

            }
        }
    }

    private void preencherTabela(DefaultTableModel model, List<Clientes> clients) {
        for (Clientes client : clients) {
            Object[] linha = {client.getId(), client.getNome(), client.getDataNascimento(), client.getId()};
            model.addRow(linha);
        }
    }

//    private void addChangeEvent() {
//        tabela.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
//            @Override
//            public void valueChanged(ListSelectionEvent event) {
//                int viewRow = tabela.getSelectedRow();
//                itemSelecionado(viewRow);
//            }
//        }
//        );
//    }
//
//    private void itemSelecionado(int linha) {
//        if (!dados.isEmpty()) {
//            linha = sorter.convertRowIndexToModel(linha);
//            ContaListagem contaSelecionada = (ContaListagem) tabela.getModel().getValueAt(linha, 0);
//            Conta conta = manager.getConta(contaSelecionada);
//            this.fechar(conta);
//        }
//
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BaixarJButton;
    private javax.swing.JTable ClientesJtable;
    private javax.swing.JLabel ClientesLabel;
    private javax.swing.JButton ListarJButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
